<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SRN Edit Information</title>
</head>
<body>
   
    <p>
        Hi, A new edit request has been generated by client. The details of the request are mentioned below:
    </p>

    <p><strong>Comments:</strong> {{ ucfirst($edit->comments) }}</p>
 
 </body>
</html>