<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SRN Revision Information</title>
</head>
<body>
   
    <p>
        Hi, a new request for revision has been generated by client. The details of the request are mentioned below:
    </p>

      <p><strong>Comments:</strong> {{ ucfirst($revision->comments) }}</p>
 
</body>
</html>